version: '3'
services:
  app:
    restart: always
    build:
      context: ../assignment-2
      dockerfile: ./Dockerfile
  proxy:
    restart: always
    image: nginx:latest
    ports:
      - 8080:8080
      - 9001:9001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
